### ISSUE TITLE
lra attention相关的代码里 没有使用任何mask来屏蔽padding token

### ISSUE THREAD

**Issue by zxgineng** [thuml/Flowformer#2]
感谢分享！
lra attention相关的代码里 好像没有任何mask来屏蔽padding token。你们的实验结果里，就是没有使用任何mask吗？

**Comment by wuhaixu2016** [comment]
Hi, we do not mask the padding tokens. If you want, you can add a mask to the newly padded token (but I do not think this will affect the performance).
