### ISSUE TITLE
add web demo/models/datasets to ICML 2022 organization on Hugging Face

### ISSUE THREAD

**Issue by AK391** [thuml/Flowformer#4]
Hi, congrats for the acceptance at ICML 2022. We are having an event on Hugging Face for ICML 2022, where you can submit spaces(web demos), models, and datasets for papers for a chance to win prizes. The hub offers free hosting and would make your work more accessible to the rest of the community. Hugging Hub works similar to github where you can push to user profiles or organization accounts, you can add the models/datasets and spaces to this organization: https://huggingface.co/ICML2022, after joining the organization using this link https://huggingface.co/organizations/ICML2022/share/BpynfJtfsOTktlmXYoKNqqCnyufKLFXuay, let me know if you need any help with the above steps, thanks.

**Comment by wuhaixu2016** [comment]
Hi, thanks a lot for your invitation. I have joined this organization.

**Comment by AK391** [comment]
@wuhaixu2016 great thanks, let me know if you need any help setting up a gradio demo for Flowformer on Hugging Face, here is how to get started https://huggingface.co/course/chapter9/1?fw=pt
