### ISSUE TITLE
关于CV版本中flow attention 的 head数量

### ISSUE THREAD

**Issue by Breeze-Zero** [thuml/Flowformer#7]
你好，很感谢你的工作，我主要将flow attention用到CV领域，但在把它放到我的模型内时，我总是会对它的head数量感到困惑，特别是在网络浅层，channel dim 为96或192时，flow attention默认的12个head数量是否太多了？

**Comment by wuhaixu2016** [comment]
是的，可以进行适当的修改。
我的一般原则是，让每个head的channel数量不少于16
